// <auto-generated />
using System;
using MIS330__GroupProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MIS330__GroupProject.Migrations
{
    [DbContext(typeof(VitalCoreDbContext))]
    [Migration("20251112203942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MIS330__GroupProject.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MembershipStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClientID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.Facility", b =>
                {
                    b.Property<int>("FacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FacilityID"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoomName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("FacilityID");

                    b.ToTable("Facility", (string)null);
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.FacilityUsage", b =>
                {
                    b.Property<int>("UsageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsageID"));

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("FacilityID")
                        .HasColumnType("int");

                    b.Property<decimal?>("FeeCharged")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SessionID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UsageDate")
                        .HasColumnType("date");

                    b.HasKey("UsageID");

                    b.HasIndex("FacilityID");

                    b.HasIndex("SessionID");

                    b.ToTable("Facility_Usage", (string)null);
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SessionID")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("SessionID");

                    b.HasIndex("TrainerID");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.SessionBooking", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<int?>("AvailabilityID")
                        .HasColumnType("int");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("FacilityID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("TotalFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TrainerID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("AvailabilityID");

                    b.HasIndex("ClientID");

                    b.HasIndex("FacilityID");

                    b.HasIndex("TrainerID");

                    b.ToTable("Session_Booking", (string)null);
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TrainerID"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("VitalcoreFee")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("TrainerID");

                    b.HasIndex("Name");

                    b.ToTable("Trainer", (string)null);
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.TrainerAvailability", b =>
                {
                    b.Property<int>("AvailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AvailabilityID"));

                    b.Property<DateTime?>("DatesAvailable")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TrainerID")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityID");

                    b.HasIndex("TrainerID");

                    b.ToTable("Trainer_Availability", (string)null);
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.FacilityUsage", b =>
                {
                    b.HasOne("MIS330__GroupProject.Models.Facility", "Facility")
                        .WithMany("FacilityUsages")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MIS330__GroupProject.Models.SessionBooking", "SessionBooking")
                        .WithMany("FacilityUsages")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Facility");

                    b.Navigation("SessionBooking");
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.Payment", b =>
                {
                    b.HasOne("MIS330__GroupProject.Models.SessionBooking", "SessionBooking")
                        .WithMany("Payments")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MIS330__GroupProject.Models.Trainer", "Trainer")
                        .WithMany("Payments")
                        .HasForeignKey("TrainerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SessionBooking");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.SessionBooking", b =>
                {
                    b.HasOne("MIS330__GroupProject.Models.TrainerAvailability", "TrainerAvailability")
                        .WithMany("SessionBookings")
                        .HasForeignKey("AvailabilityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MIS330__GroupProject.Models.Client", "Client")
                        .WithMany("SessionBookings")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MIS330__GroupProject.Models.Facility", "Facility")
                        .WithMany("SessionBookings")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MIS330__GroupProject.Models.Trainer", "Trainer")
                        .WithMany("SessionBookings")
                        .HasForeignKey("TrainerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("Facility");

                    b.Navigation("Trainer");

                    b.Navigation("TrainerAvailability");
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.TrainerAvailability", b =>
                {
                    b.HasOne("MIS330__GroupProject.Models.Trainer", "Trainer")
                        .WithMany("TrainerAvailabilities")
                        .HasForeignKey("TrainerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.Client", b =>
                {
                    b.Navigation("SessionBookings");
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.Facility", b =>
                {
                    b.Navigation("FacilityUsages");

                    b.Navigation("SessionBookings");
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.SessionBooking", b =>
                {
                    b.Navigation("FacilityUsages");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.Trainer", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SessionBookings");

                    b.Navigation("TrainerAvailabilities");
                });

            modelBuilder.Entity("MIS330__GroupProject.Models.TrainerAvailability", b =>
                {
                    b.Navigation("SessionBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
